sudo: true
language: go
go:
  - '1.7'
services:
  - rabbitmq

before_install:
  # Set up Ruby (https://github.com/travis-ci/apt-source-whitelist/issues/155)
  - travis_retry sudo apt-get -y install python-software-properties
  - travis_retry sudo apt-add-repository -y ppa:brightbox/ruby-ng
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install ruby2.3 ruby2.3-dev ruby-switch
  - sudo ruby-switch --set ruby2.3
  # Setup Glide
  - go get github.com/Masterminds/glide

install:
  - glide install
  - go build
  - gem install fluffle --version=0.2.2

before_script:
  - "ruby test/server.rb &"
  - "sleep 1"

script:
  - "go test $(glide novendor)"
